### ISSUE TITLE
"Invalid projection" happend in using function "ij2ll"

### ISSUE THREAD

**Issue by xlilium** [barronh/pseudonetcdf_examples#1]
Hi Barron,

Thanks for your contribution to "pseudonetcdf_examples".

I converted  "*.ncf" files to "*.nc" (CMAQ WRF-Like) files successfully. The purpose was to convert the CMAQ emission file into WRF-Chem emission file (such as “wrfchemi_d01_2019-09-11_00:00:00”).

I tried to use "ij2ll" in the new CMAQ WRF-Like files. But, here is the error:

**CRSError: Invalid projection: +proj=lonlat +no_defs +type=crs: (Internal Proj Error: proj_create: Error -13 (major axis or radius = 0 or not given))**

I thought it was a problem with the global attributes, which contain information about the Lambert projection.
But the CRSError happened again when I assigned global attributes to the new file.

Could you please help me with that?

Thank you.
Jin

**Comment by barronh** [comment]
If I understand you correctly, you used cmaq2wrf to convert CMAQ file to wrf-like files. Now, you want to use the wrf-like files with the ij2ll method. 

Is that right? 

Also, please show the code you used to open the file before ij2ll yielded an error.

**Comment by barronh** [comment]
I have not heard back, so I am going to close this issue.
