### ISSUE TITLE
May I want an example for CMAQ emission? 

### ISSUE THREAD

**Issue by Airwhf** [barronh/pseudonetcdf_examples#2]
Hi, Barronh,
 
These codes have help me so much. 

However, may i want an example for CMAQ emission?

I have seen it in this [url](https://pseudonetcdf.readthedocs.io/en/latest/examples/cmaqemisfromcsv.html), but it cannot work well.

I sincerely look forward to your reply， Thank you！

**Comment by barronh** [comment]
Can you be more specific? Why doesn't that example work for you?

Also, the CAMx emissions example can easily be modified. Have you looked at it?

https://github.com/barronh/pseudonetcdf_examples/tree/main/csv2camxemis

**Comment by barronh** [comment]
For the example that doesn't work, change the line

from
```
gf = pnc.pncopen('GRIDDESC', format='griddesc')
```

to


```
gf = pnc.pncopen('GRIDDESC', format='griddesc', GDNAM='12US1')
```

**Comment by Airwhf** [comment]
Hi, Barronh. Thank you for your reply.
I have changed the line 
from
```
gf = pnc.pncopen('GRIDDESC', format='griddesc')
```
to 
```
gf = pnc.pncopen('GRIDDESC', format='griddesc', GDNAM='12US1', SDATE=2016001, TSTEP=10000)
```
and this can work well.
However, the variable named TFLAG in output file (emis.nc) is all the same, such as follows.
```
2016001, 000000
2016001, 000000
2016001, 000000
...
```
Is that a right output results?
or the right results will be as follows.
```
2016001, 000000
2016001, 010000
2016001, 020000
...
```
Thank you for your reply.

**Comment by barronh** [comment]
Before the `gf.updatetflag(overwrite=True)` add

```
del gf.variables['time']
```

**Comment by barronh** [comment]
Or add the `withcf=False` to the pncopen command: 

```
gf = pnc.pncopen('GRIDDESC', format='griddesc', GDNAM='12US1', SDATE=2016001, TSTEP=10000, withcf=False)
```

Thanks for highlighting this issue.

**Comment by Airwhf** [comment]
Thank you very much. I have solved this problem according to your reply.
